[project]
name = "baseball"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"duckdb>=1.3.1",
	"pandas>=2.3.0",
	"pybaseball>=2.2.7",
	"ruff>=0.12.0",
	"tabulate>=0.9.0",
	"ty>=0.0.1a12",
]
